Repository DevCrew-proj/DevCrew-server, pull requests merged in 2024-08, with the labels that each got.

#24 feat(#23) 회원 상세 정보 등록 로직 구현
  src/main/java/com/example/devcrew/domain/auth/api/AuthApi.java
  src/main/java/com/example/devcrew/domain/auth/api/AuthController.java
  src/main/java/com/example/devcrew/domain/auth/api/dto/request/UpdateMemberRoleRequest.java
  src/main/java/com/example/devcrew/domain/auth/service/AuthService.java
  src/main/java/com/example/devcrew/domain/auth/service/SignUpService.java
  src/main/java/com/example/devcrew/domain/member/api/MemberController.java
  src/main/java/com/example/devcrew/domain/member/dto/request/UpdateCompanyMemberSignUpRequest.java
  src/main/java/com/example/devcrew/domain/member/dto/request/UpdateMemberSignUpRequest.java
  src/main/java/com/example/devcrew/domain/member/entity/CompanyMember.java
  src/main/java/com/example/devcrew/domain/member/entity/Member.java
  src/main/java/com/example/devcrew/domain/member/entity/NormalMember.java
  src/main/java/com/example/devcrew/domain/member/entity/Role.java
  src/main/java/com/example/devcrew/domain/member/service/MemberService.java
Labels: ✨ Feature

#26 feat(#20) 일반회원 포트폴리오 api 구현
  src/main/java/com/example/devcrew/domain/member/api/MemberController.java
  src/main/java/com/example/devcrew/domain/member/dto/request/PostMemberProfileRequest.java
  src/main/java/com/example/devcrew/domain/member/dto/response/GetMemberProfileResponse.java
  src/main/java/com/example/devcrew/domain/member/dto/response/PostMemberProfileResponse.java
  src/main/java/com/example/devcrew/domain/member/entity/CollegeStatus.java
  src/main/java/com/example/devcrew/domain/member/entity/HighSchoolStatus.java
  src/main/java/com/example/devcrew/domain/member/entity/Member.java
  src/main/java/com/example/devcrew/domain/member/entity/NormalMember.java
  src/main/java/com/example/devcrew/domain/member/service/MemberService.java
  src/main/java/com/example/devcrew/domain/project/api/ProjectController.java
  src/main/java/com/example/devcrew/domain/project/dto/request/PostProjectRequest.java
  src/main/java/com/example/devcrew/domain/project/dto/response/GetOneProjectResponse.java
  src/main/java/com/example/devcrew/domain/project/dto/response/GetProjectDetailResponse.java
  src/main/java/com/example/devcrew/domain/project/dto/response/GetProjectsListResponse.java
  src/main/java/com/example/devcrew/domain/project/dto/response/PostProjectResponse.java
  src/main/java/com/example/devcrew/domain/project/entity/Project.java
  src/main/java/com/example/devcrew/domain/project/entity/ProjectImage.java
  src/main/java/com/example/devcrew/domain/project/entity/ProjectTag.java
  src/main/java/com/example/devcrew/domain/project/exception/ProjectNotFoundException.java
  src/main/java/com/example/devcrew/domain/project/repository/ProjectRepository.java
  src/main/java/com/example/devcrew/domain/project/service/ProjectService.java
  src/main/java/com/example/devcrew/global/config/SwaggerConfig.java
  src/main/java/com/example/devcrew/global/error/ErrorCode.java
  src/main/resources/application.yml
Labels: ✨ Feature, 📬 API

#27 feat(#22) presigned url 설정
  build.gradle
  src/main/java/com/example/devcrew/domain/image/api/S3Controller.java
  src/main/java/com/example/devcrew/domain/image/dto/GetPresignedUrlResponse.java
  src/main/java/com/example/devcrew/domain/image/service/S3Service.java
  src/main/java/com/example/devcrew/domain/project/entity/ProjectImage.java
  src/main/java/com/example/devcrew/global/config/S3Config.java
Labels: ⚙ Setting, 📬 API

#25 Feat/#18 팀 구성하기 api 작성
  src/main/java/com/example/devcrew/domain/team/api/TeamController.java
  src/main/java/com/example/devcrew/domain/team/application/service/TeamService.java
  src/main/java/com/example/devcrew/domain/team/dto/request/ApplyTeamRequestDTO.java
  src/main/java/com/example/devcrew/domain/team/dto/request/CreateTeamRequestDTO.java
  src/main/java/com/example/devcrew/domain/team/dto/response/GetMemberInfoResponseDTO.java
  src/main/java/com/example/devcrew/domain/team/entity/Team.java
  src/main/java/com/example/devcrew/domain/team/entity/TeamMatching.java
  src/main/java/com/example/devcrew/domain/team/exception/TeamNotFoundException.java
  src/main/java/com/example/devcrew/domain/team/repository/TeamMatchingRepository.java
  src/main/java/com/example/devcrew/domain/team/repository/TeamRepository.java
  src/main/java/com/example/devcrew/global/error/ErrorCode.java
Labels: ✨ Feature, 📬 API

#37 refactor(#32) : 팀서비스, 컨트롤러 수정
  src/main/java/com/example/devcrew/domain/team/api/TeamController.java
  src/main/java/com/example/devcrew/domain/team/application/service/TeamService.java
Labels: 📬 API, 🔨 Refactor

#40 fix(#28) : cicd.yml수정위해 다른 코드 수정함
  src/main/java/com/example/devcrew/domain/project/entity/Project.java
Labels: 🐞 BugFix

#36 refactor(#35) : 이미지 여러개로 수정
  src/main/java/com/example/devcrew/domain/member/api/MemberController.java
  src/main/java/com/example/devcrew/domain/project/api/ProjectController.java
  src/main/java/com/example/devcrew/domain/project/dto/request/PostProjectRequest.java
  src/main/java/com/example/devcrew/domain/project/dto/response/GetOneProjectResponse.java
  src/main/java/com/example/devcrew/domain/project/dto/response/GetProjectDetailResponse.java
  src/main/java/com/example/devcrew/domain/project/dto/response/PostProjectResponse.java
  src/main/java/com/example/devcrew/domain/project/entity/Project.java
  src/main/java/com/example/devcrew/domain/project/entity/ProjectImage.java
  src/main/java/com/example/devcrew/domain/project/repository/ProjectImageRepository.java
  src/main/java/com/example/devcrew/domain/project/repository/ProjectRepository.java
  src/main/java/com/example/devcrew/domain/project/service/ProjectService.java
Labels: 📬 API, 🔨 Refactor

#33 Feat/#21 공모전 관련 api 구현
  src/main/java/com/example/devcrew/domain/contest/api/ContestRestController.java
  src/main/java/com/example/devcrew/domain/contest/converter/ContestConverter.java
  src/main/java/com/example/devcrew/domain/contest/dto/request/CreateContestRequestDTO.java
  src/main/java/com/example/devcrew/domain/contest/dto/response/CreateContestResponseDTO.java
  src/main/java/com/example/devcrew/domain/contest/dto/response/GetContestDetailResponseDTO.java
  src/main/java/com/example/devcrew/domain/contest/dto/response/GetContestListResponseDTO.java
  src/main/java/com/example/devcrew/domain/contest/dto/response/GetContestOneResponseDTO.java
  src/main/java/com/example/devcrew/domain/contest/entity/Contest.java
  src/main/java/com/example/devcrew/domain/contest/exception/ContestNotFoundException.java
  src/main/java/com/example/devcrew/domain/contest/repository/ContestRepository.java
  src/main/java/com/example/devcrew/domain/contest/service/ContestCommandService.java
  src/main/java/com/example/devcrew/domain/contest/service/ContestCommandServiceImpl.java
  src/main/java/com/example/devcrew/domain/contest/service/ContestQueryService.java
  src/main/java/com/example/devcrew/domain/contest/service/ContestQueryServiceImpl.java
  src/main/java/com/example/devcrew/domain/member/entity/CollegeStatus.java
  src/main/java/com/example/devcrew/global/error/ErrorCode.java
Labels: ✨ Feature

#45 Refactor/#39 팀 신청하기 api 수정
  src/main/java/com/example/devcrew/domain/team/api/TeamController.java
  src/main/java/com/example/devcrew/domain/team/dto/request/ApplyTeamRequestDTO.java
  src/main/java/com/example/devcrew/domain/team/dto/request/CreateTeamRequestDTO.java
  src/main/java/com/example/devcrew/domain/team/entity/Team.java
  src/main/java/com/example/devcrew/domain/team/entity/TeamMatching.java
  src/main/java/com/example/devcrew/domain/team/exception/InvalidTeamPasswordException.java
  src/main/java/com/example/devcrew/domain/team/repository/TeamRepository.java
  src/main/java/com/example/devcrew/domain/team/service/TeamService.java
  src/main/java/com/example/devcrew/global/error/ErrorCode.java
Labels: 📬 API, 🔨 Refactor, 🙋‍♂️ Question

#48 fix(#47) : successresponse에 status 추가
  src/main/java/com/example/devcrew/domain/member/api/MemberController.java
  src/main/java/com/example/devcrew/domain/project/api/ProjectController.java
  src/main/java/com/example/devcrew/global/response/SuccessResponse.java
  src/main/java/com/example/devcrew/global/response/SuccessResponseAdvice.java
Labels: 🔨 Refactor

#51 feat(#50) project paging구현
  src/main/java/com/example/devcrew/domain/project/api/ProjectController.java
  src/main/java/com/example/devcrew/domain/project/entity/Project.java
  src/main/java/com/example/devcrew/domain/project/entity/ProjectTag.java
  src/main/java/com/example/devcrew/domain/project/repository/ProjectRepository.java
  src/main/java/com/example/devcrew/domain/project/service/ProjectService.java
  src/main/java/com/example/devcrew/global/error/ErrorCode.java
Labels: ✨ Feature, 📬 API

#54 Refactor(#53) : 공모전 API 수정
  src/main/java/com/example/devcrew/domain/contest/api/ContestRestController.java
  src/main/java/com/example/devcrew/domain/contest/converter/ContestConverter.java
  src/main/java/com/example/devcrew/domain/contest/exception/AcceptancePeriodInvalidException.java
  src/main/java/com/example/devcrew/domain/contest/exception/ContestNotFoundException.java
  src/main/java/com/example/devcrew/domain/contest/service/ContestCommandServiceImpl.java
  src/main/java/com/example/devcrew/global/error/ErrorCode.java
  src/main/java/com/example/devcrew/global/error/GlobalExceptionHandler.java
Labels: 📬 API, 🔨 Refactor

#49 Feat/#46 공모전 정보 조회 구현
  src/main/java/com/example/devcrew/domain/team/api/TeamController.java
  src/main/java/com/example/devcrew/domain/team/entity/Team.java
  src/main/java/com/example/devcrew/domain/team/entity/TeamMatching.java
  src/main/java/com/example/devcrew/domain/team/service/TeamService.java
Labels: ✨ Feature, 📬 API

#57 Feat(#56): WebConfig 구현
  src/main/java/com/example/devcrew/global/config/WebConfig.java
Labels: ✨ Feature

#61 fix(#60): period->duration
  src/main/java/com/example/devcrew/domain/project/api/ProjectController.java
  src/main/java/com/example/devcrew/domain/project/dto/request/PostProjectRequest.java
  src/main/java/com/example/devcrew/domain/project/dto/response/GetOneProjectResponse.java
  src/main/java/com/example/devcrew/domain/project/dto/response/GetProjectDetailResponse.java
  src/main/java/com/example/devcrew/domain/project/dto/response/PostProjectResponse.java
  src/main/java/com/example/devcrew/domain/project/entity/Project.java
Labels: 🔨 Refactor

#62 Refactor(#55) : 댓글 페이지네이션 구현
  src/main/java/com/example/devcrew/domain/comment/api/CommentController.java
  src/main/java/com/example/devcrew/domain/comment/converter/CommentConverter.java
  src/main/java/com/example/devcrew/domain/comment/dto/response/GetCommentResponseDTO.java
  src/main/java/com/example/devcrew/domain/comment/repository/AdviceCommentRepository.java
  src/main/java/com/example/devcrew/domain/comment/repository/CodeCommentRepository.java
  src/main/java/com/example/devcrew/domain/comment/repository/DesignCommentRepository.java
  src/main/java/com/example/devcrew/domain/comment/repository/PlanCommentRepository.java
  src/main/java/com/example/devcrew/domain/comment/service/ReadCommentImpl.java
  src/main/java/com/example/devcrew/domain/feedback/api/FeedbackController.java
Labels: 🔨 Refactor

#64 Feat(#63) : 게시판 댓글 사용자 이미지 받기
  src/main/java/com/example/devcrew/domain/comment/converter/CommentConverter.java
  src/main/java/com/example/devcrew/domain/comment/dto/response/SingleCommentResponseDTO.java
  src/main/java/com/example/devcrew/domain/feedback/converter/AdviceFeedbackConverter.java
  src/main/java/com/example/devcrew/domain/feedback/converter/CodeFeedbackConverter.java
  src/main/java/com/example/devcrew/domain/feedback/converter/DesignFeedbackConverter.java
  src/main/java/com/example/devcrew/domain/feedback/converter/PlanFeedbackConverter.java
  src/main/java/com/example/devcrew/domain/feedback/dto/response/advicefeedback/ReadAdviceFeedbackResponseDTO.java
  src/main/java/com/example/devcrew/domain/feedback/dto/response/codefeedback/ReadCodeFeedbackResponseDTO.java
  src/main/java/com/example/devcrew/domain/feedback/dto/response/designfeedback/ReadDesignFeedbackResponseDTO.java
  src/main/java/com/example/devcrew/domain/feedback/dto/response/planfeedback/ReadPlanFeedbackResponseDTO.java
Labels: ✨ Feature, 🔨 Refactor

#66 Feat(#65) : 댓글 카운터 구현, 코드리뷰/현직자 조언 전체 조회 api 구현
  src/main/java/com/example/devcrew/domain/comment/repository/AdviceCommentRepository.java
  src/main/java/com/example/devcrew/domain/comment/repository/CodeCommentRepository.java
  src/main/java/com/example/devcrew/domain/comment/repository/DesignCommentRepository.java
  src/main/java/com/example/devcrew/domain/comment/repository/PlanCommentRepository.java
  src/main/java/com/example/devcrew/domain/feedback/api/FeedbackController.java
  src/main/java/com/example/devcrew/domain/feedback/converter/AdviceFeedbackConverter.java
  src/main/java/com/example/devcrew/domain/feedback/converter/CodeFeedbackConverter.java
  src/main/java/com/example/devcrew/domain/feedback/converter/DesignFeedbackConverter.java
  src/main/java/com/example/devcrew/domain/feedback/converter/PlanFeedbackConverter.java
  src/main/java/com/example/devcrew/domain/feedback/dto/response/advicefeedback/ReadAdviceFeedbackResponseDTO.java
  src/main/java/com/example/devcrew/domain/feedback/dto/response/codefeedback/ReadCodeFeedbackResponseDTO.java
  src/main/java/com/example/devcrew/domain/feedback/dto/response/designfeedback/ReadDesignFeedbackResponseDTO.java
  src/main/java/com/example/devcrew/domain/feedback/dto/response/planfeedback/ReadPlanFeedbackResponseDTO.java
  src/main/java/com/example/devcrew/domain/feedback/repository/AdviceFeedbackRepository.java
  src/main/java/com/example/devcrew/domain/feedback/repository/CodeFeedbackRepository.java
  src/main/java/com/example/devcrew/domain/feedback/service/ReadAdviceFeedbackImpl.java
  src/main/java/com/example/devcrew/domain/feedback/service/ReadCodeFeedbackImpl.java
  src/main/java/com/example/devcrew/domain/feedback/service/ReadDesignFeedbackImpl.java
  src/main/java/com/example/devcrew/domain/feedback/service/ReadPlanFeedbackImpl.java
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#70 Refactor(#69): 게시글 응답 DTO 수정
  src/main/java/com/example/devcrew/domain/feedback/converter/AdviceFeedbackConverter.java
  src/main/java/com/example/devcrew/domain/feedback/converter/CodeFeedbackConverter.java
  src/main/java/com/example/devcrew/domain/feedback/dto/response/advicefeedback/ReadAdviceFeedbackResponseDTO.java
  src/main/java/com/example/devcrew/domain/feedback/dto/response/codefeedback/ReadCodeFeedbackResponseDTO.java
Labels: 🔨 Refactor

#72 fix(#71) : WebConfig 파일 수정
  src/main/java/com/example/devcrew/global/config/WebConfig.java
Labels: ⚙ Setting

#74 Feat(#73) 로그인 성공 후 프론트로 리다이렉트
  src/main/java/com/example/devcrew/global/oauth2/OAuthAttributes.java
  src/main/java/com/example/devcrew/global/oauth2/handler/OAuth2LoginSuccessHandler.java
Labels: ✨ Feature

#76 Refactor(#75) 게시글 응답dto 수정
  src/main/java/com/example/devcrew/domain/feedback/converter/AdviceFeedbackConverter.java
  src/main/java/com/example/devcrew/domain/feedback/converter/CodeFeedbackConverter.java
  src/main/java/com/example/devcrew/domain/feedback/converter/DesignFeedbackConverter.java
  src/main/java/com/example/devcrew/domain/feedback/converter/PlanFeedbackConverter.java
  src/main/java/com/example/devcrew/domain/feedback/dto/response/advicefeedback/ReadAdviceFeedbackListResponseDTO.java
  src/main/java/com/example/devcrew/domain/feedback/dto/response/advicefeedback/ReadAdviceFeedbackResponseDTO.java
  src/main/java/com/example/devcrew/domain/feedback/dto/response/codefeedback/ReadCodeFeedbackListResponseDTO.java
  src/main/java/com/example/devcrew/domain/feedback/dto/response/codefeedback/ReadCodeFeedbackResponseDTO.java
  src/main/java/com/example/devcrew/domain/feedback/dto/response/designfeedback/ReadDesignFeedbackListResponseDTO.java
  src/main/java/com/example/devcrew/domain/feedback/dto/response/designfeedback/ReadDesignFeedbackResponseDTO.java
  src/main/java/com/example/devcrew/domain/feedback/dto/response/planfeedback/ReadPlanFeedbackListResponseDTO.java
  src/main/java/com/example/devcrew/domain/feedback/dto/response/planfeedback/ReadPlanFeedbackResponseDTO.java
  src/main/java/com/example/devcrew/domain/feedback/entity/FeedbackTag.java
  src/main/java/com/example/devcrew/domain/feedback/entity/Language.java
  src/main/java/com/example/devcrew/domain/feedback/service/ReadAdviceFeedbackImpl.java
  src/main/java/com/example/devcrew/domain/feedback/service/ReadCodeFeedbackImpl.java
Labels: 🔨 Refactor

#78 refactor(#77) : member api swagger description 추가
  src/main/java/com/example/devcrew/domain/member/api/MemberController.java
Labels: 🔨 Refactor

#82 Refactor(#81): 예외처리 추가
  src/main/java/com/example/devcrew/domain/comment/exception/CommentFeedbackNotFoundException.java
  src/main/java/com/example/devcrew/domain/comment/exception/CommentMemberNotFoundException.java
  src/main/java/com/example/devcrew/domain/comment/service/CreateCommentImpl.java
  src/main/java/com/example/devcrew/domain/feedback/exception/FeedbackNotFoundException.java
  src/main/java/com/example/devcrew/domain/feedback/service/CreateAdviceFeedbackImpl.java
  src/main/java/com/example/devcrew/domain/feedback/service/CreateCodeFeedbackImpl.java
  src/main/java/com/example/devcrew/domain/feedback/service/CreateDesignFeedbackImpl.java
  src/main/java/com/example/devcrew/domain/feedback/service/CreatePlanFeedbackImpl.java
  src/main/java/com/example/devcrew/domain/feedback/service/ReadAdviceFeedbackImpl.java
  src/main/java/com/example/devcrew/domain/feedback/service/ReadCodeFeedbackImpl.java
  src/main/java/com/example/devcrew/domain/feedback/service/ReadDesignFeedbackImpl.java
  src/main/java/com/example/devcrew/domain/feedback/service/ReadPlanFeedbackImpl.java
  src/main/java/com/example/devcrew/global/error/ErrorCode.java
Labels: 🔨 Refactor

#84 Refactor(#83) : 댓글api 수정
  src/main/java/com/example/devcrew/domain/comment/api/CommentController.java
  src/main/java/com/example/devcrew/domain/comment/service/CreateCommentImpl.java
Labels: 📬 API, 🔨 Refactor

#86 Feat(#85): 회원 이름 제공 API
  src/main/java/com/example/devcrew/domain/member/api/MemberController.java
  src/main/java/com/example/devcrew/domain/member/dto/response/GetMemberNameResponse.java
  src/main/java/com/example/devcrew/domain/member/service/MemberService.java
Labels: ✨ Feature

#88 refactor(#87): 댓글길이 제한
  src/main/java/com/example/devcrew/domain/comment/entity/AdviceComment.java
  src/main/java/com/example/devcrew/domain/comment/entity/CodeComment.java
  src/main/java/com/example/devcrew/domain/comment/entity/DesignComment.java
  src/main/java/com/example/devcrew/domain/comment/entity/PlanComment.java
Labels: 🔨 Refactor

#92 refactor(#90): totalPages, totalElements 추가
  src/main/java/com/example/devcrew/domain/project/dto/response/GetProjectsListResponse.java
  src/main/java/com/example/devcrew/domain/project/service/ProjectService.java
Labels: 📬 API, 🔨 Refactor

#96 feat(#95) : TimeZoneConfig 한국시간 설정
  src/main/java/com/example/devcrew/global/config/TimeZoneConfig.java
Labels: ✨ Feature

#98 Refactor(#97) 기업 회원 등록 로직 수정
  src/main/java/com/example/devcrew/domain/contest/converter/ContestConverter.java
  src/main/java/com/example/devcrew/domain/member/dto/request/UpdateCompanyMemberSignUpRequest.java
  src/main/java/com/example/devcrew/domain/member/entity/CompanyMember.java
  src/main/java/com/example/devcrew/domain/member/entity/CompanySize.java
  src/main/java/com/example/devcrew/domain/member/entity/Member.java
  src/main/java/com/example/devcrew/domain/member/service/MemberService.java
Labels: ✨ Feature, 🔨 Refactor

#102 Fix(#101) 담당자 이메일 등록되도록 수정
  src/main/java/com/example/devcrew/domain/member/dto/request/UpdateCompanyMemberSignUpRequest.java
Labels: 🐞 BugFix

#110 refactor(#109) : 프로젝트 조회 -카테고리+전체 분리
  src/main/java/com/example/devcrew/domain/project/api/ProjectController.java
  src/main/java/com/example/devcrew/domain/project/repository/ProjectRepository.java
  src/main/java/com/example/devcrew/domain/project/service/ProjectService.java
Labels: 📬 API, 🔨 Refactor

#115 Refactor/#113 팀신청하기 api 수정
  src/main/java/com/example/devcrew/domain/team/api/TeamController.java
  src/main/java/com/example/devcrew/domain/team/dto/request/ApplyTeamRequestDTO.java
  src/main/java/com/example/devcrew/domain/team/entity/Os.java
  src/main/java/com/example/devcrew/domain/team/repository/TeamRepository.java
  src/main/java/com/example/devcrew/domain/team/service/TeamService.java
Labels: ✨ Feature

#119 Refactor#118 팀구성하기 dto 수정
  src/main/java/com/example/devcrew/domain/team/dto/request/CreateTeamRequestDTO.java
  src/main/java/com/example/devcrew/domain/team/entity/Team.java
  src/main/java/com/example/devcrew/domain/team/service/TeamService.java
Labels: 🔨 Refactor

#121 refactor#120 : 중복되는 팀 저장 및 조회 막음
  src/main/java/com/example/devcrew/domain/team/exception/DuplicateTeamException.java
  src/main/java/com/example/devcrew/domain/team/repository/TeamRepository.java
  src/main/java/com/example/devcrew/domain/team/service/TeamService.java
  src/main/java/com/example/devcrew/global/error/ErrorCode.java
Labels: ✨ Feature, 🔨 Refactor

#123 refactor#122: 컨버터수정
  src/main/java/com/example/devcrew/domain/contest/converter/ContestConverter.java
Labels: 🔨 Refactor

#129 chore(#128): dockerfile 수정 - timezone 설정 for 로그
  Dockerfile
Labels: 📦 chore

#131 refactor(#130) : 한줄 요약 추가
  src/main/java/com/example/devcrew/domain/project/dto/request/PostProjectRequest.java
  src/main/java/com/example/devcrew/domain/project/dto/response/GetOneProjectResponse.java
  src/main/java/com/example/devcrew/domain/project/dto/response/GetProjectDetailResponse.java
  src/main/java/com/example/devcrew/domain/project/dto/response/PostProjectResponse.java
  src/main/java/com/example/devcrew/domain/project/entity/Project.java
Labels: 🔨 Refactor

#136 refactor(#135): role 추가
  src/main/java/com/example/devcrew/domain/project/dto/response/GetOneProjectResponse.java
  src/main/java/com/example/devcrew/domain/project/service/ProjectService.java
Labels: 🔨 Refactor

#137 Refactor#134 팀매칭 api 수정
  src/main/java/com/example/devcrew/domain/team/dto/request/ApplyTeamRequestDTO.java
  src/main/java/com/example/devcrew/domain/team/repository/TeamRepository.java
  src/main/java/com/example/devcrew/domain/team/service/TeamService.java
Labels: 🔨 Refactor

#146 chore(#145): dockerfile-시간-수정
  Dockerfile
Labels: 📦 chore
