Repository DevCrew-proj/DevCrew-server, pull requests merged in 2024-07, with the labels that each got.

#5 feat(#2) .gitignore 파일 + BaseTimeEntity 클래스 구현
  .gitignore
  src/main/java/com/example/devcrew/DevcrewApplication.java
  src/main/java/com/example/devcrew/global/common/BaseTimeEntity.java
Labels: ⚙ Setting, ✨ Feature

#7 Feat(#1) SpringSecurity 및 카카오 소셜 로그인 구현 + Swagger 설정
  .github/pull_request_template.md
  build.gradle
  src/main/java/com/example/devcrew/domain/auth/api/AuthApi.java
  src/main/java/com/example/devcrew/domain/auth/api/AuthController.java
  src/main/java/com/example/devcrew/domain/auth/service/AuthService.java
  src/main/java/com/example/devcrew/domain/auth/service/SignUpService.java
  src/main/java/com/example/devcrew/domain/member/dto/request/UpdateMemberSignUpRequest.java
  src/main/java/com/example/devcrew/domain/member/entity/Member.java
  src/main/java/com/example/devcrew/domain/member/entity/Role.java
  src/main/java/com/example/devcrew/domain/member/entity/SocialType.java
  src/main/java/com/example/devcrew/domain/member/entity/Status.java
  src/main/java/com/example/devcrew/domain/member/exception/MemberNotFoundException.java
  src/main/java/com/example/devcrew/domain/member/repository/MemberRepository.java
  src/main/java/com/example/devcrew/global/config/SecurityConfig.java
  src/main/java/com/example/devcrew/global/config/SwaggerConfig.java
  src/main/java/com/example/devcrew/global/error/ErrorCode.java
  src/main/java/com/example/devcrew/global/error/ErrorResponse.java
  src/main/java/com/example/devcrew/global/error/GlobalExceptionHandler.java
  src/main/java/com/example/devcrew/global/error/advice/AdviceException.java
  src/main/java/com/example/devcrew/global/error/exception/BusinessException.java
  src/main/java/com/example/devcrew/global/jwt/exception/NotFoundTokenException.java
  src/main/java/com/example/devcrew/global/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/example/devcrew/global/jwt/refresh/domain/RefreshToken.java
  src/main/java/com/example/devcrew/global/jwt/refresh/repository/RefreshTokenRepository.java
  src/main/java/com/example/devcrew/global/jwt/refresh/service/RefreshTokenService.java
  src/main/java/com/example/devcrew/global/jwt/service/JwtService.java
  src/main/java/com/example/devcrew/global/jwt/util/PasswordUtil.java
  src/main/java/com/example/devcrew/global/oauth2/CustomOAuth2User.java
  src/main/java/com/example/devcrew/global/oauth2/OAuthAttributes.java
  src/main/java/com/example/devcrew/global/oauth2/filter/CustomJsonUsernamePasswordAuthenticationFilter.java
  src/main/java/com/example/devcrew/global/oauth2/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/example/devcrew/global/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/example/devcrew/global/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/example/devcrew/global/oauth2/userInfo/GoogleOAuth2UserInfo.java
  src/main/java/com/example/devcrew/global/oauth2/userInfo/KakaoOAuth2UserInfo.java
  src/main/java/com/example/devcrew/global/oauth2/userInfo/OAuth2UserInfo.java
  src/main/java/com/example/devcrew/global/query/QueryService.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ✨ Feature

#11 feat(#6) : Feedback, Comment, FeedbackImage 엔티티 구현
  src/main/java/com/example/devcrew/domain/comment/entity/Comment.java
  src/main/java/com/example/devcrew/domain/feedback/entity/Feedback.java
  src/main/java/com/example/devcrew/domain/feedback/entity/FeedbackImage.java
  src/main/java/com/example/devcrew/domain/feedback/entity/FeedbackTag.java
  src/main/java/com/example/devcrew/domain/feedback/entity/Language.java
Labels: ✨ Feature

#12 feat(#4) : 포트폴리오 구현
  .gitignore
  build.gradle
  src/main/java/com/example/devcrew/domain/project/domain/Project.java
  src/main/java/com/example/devcrew/domain/project/domain/ProjectImage.java
  src/main/java/com/example/devcrew/domain/project/domain/ProjectTag.java
  src/main/java/com/example/devcrew/domain/project/dto/GetProjectDetailResponse.java
  src/main/java/com/example/devcrew/domain/project/dto/UpdateProjectRequest.java
  src/main/java/com/example/devcrew/domain/project/repository/ProjectRepository.java
Labels: ✨ Feature

#14 feat(#13) : 회원 엔티티 상세 구현
  src/main/java/com/example/devcrew/domain/member/entity/CompanyMember.java
  src/main/java/com/example/devcrew/domain/member/entity/CompanySize.java
  src/main/java/com/example/devcrew/domain/member/entity/Gender.java
  src/main/java/com/example/devcrew/domain/member/entity/Member.java
  src/main/java/com/example/devcrew/domain/member/entity/NormalMember.java
  src/main/java/com/example/devcrew/domain/member/entity/SchoolStatus.java
Labels: ✨ Feature

#15 feat(#8): Team, TeamMatching entity 구현
  src/main/java/com/example/devcrew/domain/team/entity/Objective.java
  src/main/java/com/example/devcrew/domain/team/entity/Os.java
  src/main/java/com/example/devcrew/domain/team/entity/Team.java
  src/main/java/com/example/devcrew/domain/team/entity/TeamMatching.java
Labels: ✨ Feature

#17 Feat(#16) cicd배포
  .gitignore
  Dockerfile
  src/main/java/com/example/devcrew/domain/project/api/ProjectController.java
  src/main/resources/application-local.yml
Labels: ⚙ Setting
